-- 20260102194500_multi_tenant_schema.sql

-- 1. Organizations
CREATE TABLE IF NOT EXISTS "public"."organizations" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" text NOT NULL,
    "plan" text DEFAULT 'free',
    "settings" jsonb DEFAULT '{}',
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id")
);

-- 2. Global Profiles (Split from Auth)
CREATE TABLE IF NOT EXISTS "public"."user_profiles" (
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "full_name" text,
    "email" text,
    "avatar_url" text,
    PRIMARY KEY ("user_id")
);

-- 3. Org Members
CREATE TABLE IF NOT EXISTS "public"."org_members" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "organization_id" bigint NOT NULL REFERENCES "public"."organizations"("id") ON DELETE CASCADE,
    "user_id" uuid NOT NULL REFERENCES "public"."user_profiles"("user_id") ON DELETE CASCADE,
    "role" text NOT NULL DEFAULT 'member', -- owner, admin, member
    "status" text NOT NULL DEFAULT 'active',
    "created_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("id"),
    UNIQUE ("organization_id", "user_id")
);

-- 4. Teams
CREATE TABLE IF NOT EXISTS "public"."teams" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "organization_id" bigint NOT NULL REFERENCES "public"."organizations"("id") ON DELETE CASCADE,
    "name" text NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "public"."team_members" (
    "team_id" bigint NOT NULL REFERENCES "public"."teams"("id") ON DELETE CASCADE,
    "org_member_id" bigint NOT NULL REFERENCES "public"."org_members"("id") ON DELETE CASCADE,
    "role" text DEFAULT 'member',
    PRIMARY KEY ("team_id", "org_member_id")
);

-- 5. Deal Stages
CREATE TABLE IF NOT EXISTS "public"."deal_stages" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "organization_id" bigint NOT NULL REFERENCES "public"."organizations"("id") ON DELETE CASCADE,
    "label" text NOT NULL,
    "probability" integer DEFAULT 0,
    "sort_order" integer DEFAULT 0,
    PRIMARY KEY ("id")
);

-- 6. Invitation System
CREATE TABLE IF NOT EXISTS "public"."organization_invites" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "organization_id" bigint NOT NULL REFERENCES "public"."organizations"("id") ON DELETE CASCADE,
    "email" text NOT NULL,
    "role" text NOT NULL DEFAULT 'member',
    "token_hash" text NOT NULL,
    "status" text DEFAULT 'pending', -- pending, accepted, expired
    "created_at" timestamp with time zone DEFAULT now(),
    "expires_at" timestamp with time zone NOT NULL,
    "used_at" timestamp with time zone,
    PRIMARY KEY ("id")
);

-- 7. Add Tenant ID to Core Tables (Nullable for now to allow backfill)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'companies' AND column_name = 'organization_id') THEN
        ALTER TABLE "public"."companies" ADD COLUMN "organization_id" bigint REFERENCES "public"."organizations"("id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contacts' AND column_name = 'organization_id') THEN
        ALTER TABLE "public"."contacts" ADD COLUMN "organization_id" bigint REFERENCES "public"."organizations"("id");
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'deals' AND column_name = 'organization_id') THEN
        ALTER TABLE "public"."deals" ADD COLUMN "organization_id" bigint REFERENCES "public"."organizations"("id");
        ALTER TABLE "public"."deals" ADD COLUMN "stage_id" bigint REFERENCES "public"."deal_stages"("id"); 
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'tasks' AND column_name = 'organization_id') THEN
        ALTER TABLE "public"."tasks" ADD COLUMN "organization_id" bigint REFERENCES "public"."organizations"("id");
    END IF;
END $$;

-- 8. Add JSONB Custom Data
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'companies' AND column_name = 'custom_data') THEN
        ALTER TABLE "public"."companies" ADD COLUMN "custom_data" jsonb DEFAULT '{}';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'contacts' AND column_name = 'custom_data') THEN
        ALTER TABLE "public"."contacts" ADD COLUMN "custom_data" jsonb DEFAULT '{}';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'deals' AND column_name = 'custom_data') THEN
        ALTER TABLE "public"."deals" ADD COLUMN "custom_data" jsonb DEFAULT '{}';
    END IF;
END $$;

-- 9. Mandatory Indexes
CREATE INDEX IF NOT EXISTS idx_companies_org ON "public"."companies" ("organization_id");
CREATE INDEX IF NOT EXISTS idx_contacts_org ON "public"."contacts" ("organization_id");
CREATE INDEX IF NOT EXISTS idx_deals_org ON "public"."deals" ("organization_id");
CREATE INDEX IF NOT EXISTS idx_tasks_org ON "public"."tasks" ("organization_id");
CREATE INDEX IF NOT EXISTS idx_deals_custom_gin ON "public"."deals" USING GIN ("custom_data" jsonb_path_ops);

-- 10. Backfill Demo Data (If Empty)
DO $$
DECLARE
    demo_org_id bigint;
    default_user_id uuid;
BEGIN
    -- Create Demo Org if not exists
    IF NOT EXISTS (SELECT 1 FROM "public"."organizations") THEN
        INSERT INTO "public"."organizations" (name) VALUES ('Demo Organization') RETURNING id INTO demo_org_id;
    ELSE
        SELECT id INTO demo_org_id FROM "public"."organizations" LIMIT 1;
    END IF;

    -- Backfill Null Org IDs
    UPDATE "public"."companies" SET organization_id = demo_org_id WHERE organization_id IS NULL;
    UPDATE "public"."contacts" SET organization_id = demo_org_id WHERE organization_id IS NULL;
    UPDATE "public"."deals" SET organization_id = demo_org_id WHERE organization_id IS NULL;
    UPDATE "public"."tasks" SET organization_id = demo_org_id WHERE organization_id IS NULL;

    -- Initialize User Profiles from Auth (Best effort for dev environment)
    INSERT INTO "public"."user_profiles" (user_id, email)
    SELECT id, email FROM auth.users
    ON CONFLICT (user_id) DO NOTHING;

    -- Add existing users to Demo Org as Owners
    INSERT INTO "public"."org_members" (organization_id, user_id, role)
    SELECT demo_org_id, id, 'owner'
    FROM auth.users
    ON CONFLICT (organization_id, user_id) DO NOTHING;

END $$;
